with open('create_pico_board.py', 'r') as file:
    print("var groveLibraryFunctionString = '#Code automatically generated by BIPES (http://www.bipes.net.br)\n'")
    lines = file.readlines()  # Reads all lines into a list
    for line in lines:
        print("groveLibraryFunctionString+=" + repr(line))
